### ISSUE TITLE
Unable to Search Images

### ISSUE THREAD

**Issue by vguleria1108** [sethuiyer/Image-to-Image-search#14]
Whenever I am trying to search image following error occurs.
E0130 17:26:31.418057 123145353228288 app.py:1780] Exception on /search [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 78, in search
    answers = description_search(query)
  File "server.py", line 28, in description_search
    hitCount = results['hits']['total']['value']
TypeError: 'int' object is not subscriptable
I0130 17:26:31.419389 123145353228288 _internal.py:122] 127.0.0.1 - - [30/Jan/2020 17:26:31] "POST /search HTTP/1.1" 500 -

**Comment by sethuiyer** [comment]
Can you mention the version number of elastic search you are using? if it's latest, I'll upgrade the code to match the latest version.

**Comment by jimmybytes** [comment]
The same error message
```
elasticsearch:6.6.0
```

**Comment by jimmybytes** [comment]
edit server.py, it's working
```
...
hitCount = results['hits']['total']['value'] -> hitCount = results['hits']['total']
...
```

**Comment by vguleria1108** [comment]
@
