### ISSUE TITLE
NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index')

### ISSUE THREAD

**Issue by anshul12112** [sethuiyer/Image-to-Image-search#4]
F = np.row_stack(x['image']['feat'] for x in batch)
GET http://localhost:9200/desearch/_search [status:404 request:0.118s]
[2019-04-11 00:45:39,134] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 61, in index
    answers = description_search(query)
  File "server.py", line 31, in description_search
    "match": {"description": query}
  File "/home/anshul/.local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/anshul/.local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 660, in search
    doc_type, '_search'), params=params, body=body)
  File "/home/anshul/.local/lib/python3.6/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/anshul/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/anshul/.local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    **raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index')**
127.0.0.1 - - [11/Apr/2019 00:45:39] "POST / HTTP/1.1" 500 -

**Comment by sethuiyer** [comment]
Start the elastic search service followed by python index_database.py as per the new release.

Kindly check the new release where the reliance of dataset.json has been completely eliminated.
