### ISSUE TITLE
raise JSONDecodeError("Expecting value", s, err.value) from None

### ISSUE THREAD

**Issue by anshul12112** [sethuiyer/Image-to-Image-search#5]
Sir, i am very thankful to you. you help me in resolving issue but sir still whole issue is not resolved while running custom_index.py i am getting following error .please sir help me
Traceback (most recent call last):
File "custom_index.py", line 25, in
data = json.load(f)
File "/usr/lib/python3.6/json/init.py", line 299, in load
parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
File "/usr/lib/python3.6/json/init.py", line 354, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by sethuiyer** [comment]
Kindly check the new release where the reliance of dataset.json has been completely eliminated.
